version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: python3 src/my_sum.py
  unit-test:
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: python -m unittest discover test/unit
  integration-test:
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: python -m unittest discover test/integration
  component-test:
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: python -m unittest discover test/component
  e2e-test:
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: python -m unittest discover test/component
  deploy-dev:
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: echo "deployment started in $CURRENT_ENV"
      - run: echo "deployment successful"
  deploy-prod:
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: echo "deployment started in $CURRENT_ENV"
      - run: echo "deployment successful"

workflows:
  main:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - integration-test:
          requires:
            - build
      - component-test:
          requires:
            - build
      - deploy-dev:
          context: demo-dev
          requires:
            - unit-test
            - integration-test
            - component-test
      - approve-deploy-to-prod:
          type: approval
          requires:
            - deploy-dev
      - deploy-prod:
          context: demo-prod
          requires:
            - approve-deploy-to-prod

  daily-e2e-workflow:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ "Daily E2E test", << pipeline.schedule.name >> ]
    jobs:
      - build
      - e2e-test:
          requires:
            - build